/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatementsRouteImport } from './routes/statements'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatementsIndexRouteImport } from './routes/statements.index'
import { Route as StatementsIdRouteImport } from './routes/statements.$id'

const StatementsRoute = StatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsIndexRoute = StatementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatementsRoute,
} as any)
const StatementsIdRoute = StatementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StatementsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deals': typeof DealsRoute
  '/performance': typeof PerformanceRoute
  '/statements': typeof StatementsRouteWithChildren
  '/statements/$id': typeof StatementsIdRoute
  '/statements/': typeof StatementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deals': typeof DealsRoute
  '/performance': typeof PerformanceRoute
  '/statements/$id': typeof StatementsIdRoute
  '/statements': typeof StatementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deals': typeof DealsRoute
  '/performance': typeof PerformanceRoute
  '/statements': typeof StatementsRouteWithChildren
  '/statements/$id': typeof StatementsIdRoute
  '/statements/': typeof StatementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/deals'
    | '/performance'
    | '/statements'
    | '/statements/$id'
    | '/statements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/deals'
    | '/performance'
    | '/statements/$id'
    | '/statements'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/deals'
    | '/performance'
    | '/statements'
    | '/statements/$id'
    | '/statements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DealsRoute: typeof DealsRoute
  PerformanceRoute: typeof PerformanceRoute
  StatementsRoute: typeof StatementsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statements': {
      id: '/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof StatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statements/': {
      id: '/statements/'
      path: '/'
      fullPath: '/statements/'
      preLoaderRoute: typeof StatementsIndexRouteImport
      parentRoute: typeof StatementsRoute
    }
    '/statements/$id': {
      id: '/statements/$id'
      path: '/$id'
      fullPath: '/statements/$id'
      preLoaderRoute: typeof StatementsIdRouteImport
      parentRoute: typeof StatementsRoute
    }
  }
}

interface StatementsRouteChildren {
  StatementsIdRoute: typeof StatementsIdRoute
  StatementsIndexRoute: typeof StatementsIndexRoute
}

const StatementsRouteChildren: StatementsRouteChildren = {
  StatementsIdRoute: StatementsIdRoute,
  StatementsIndexRoute: StatementsIndexRoute,
}

const StatementsRouteWithChildren = StatementsRoute._addFileChildren(
  StatementsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DealsRoute: DealsRoute,
  PerformanceRoute: PerformanceRoute,
  StatementsRoute: StatementsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
